package selenium;
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;

import java.time.Duration;

import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Dimension;


public class Demo1Test {
	WebDriver driver;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
    }

    @Test
    public void demo1() {

        driver.get("https://the-internet.herokuapp.com/login");
        driver.manage().window().setSize(new Dimension(550, 692));

        js.executeScript("document.getElementById('username').value='tomsmith';");
        js.executeScript("document.getElementById('password').value='SuperSecretPassword!';");

        driver.findElement(By.cssSelector("button[type='submit']")).click();
        String message = driver.findElement(By.id("flash")).getText();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));
        if (message.contains("You logged into a secure area")) {
            System.out.println("✅ Login Test Passed");
        } else {
            System.out.println("❌ Login Test Failed");
        }


    }

    @After
    public void tearDown() {
        driver.quit();

	}

}
